# Generated by Django 2.0.3 on 2018-09-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insidepages', '0002_auto_20180927_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='insidepages.MixPost'),
        ),
    ]
