# Generated by Django 2.1.1 on 2018-09-28 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insidepages', '0006_auto_20180928_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textver2',
            old_name='text',
            new_name='full',
        ),
    ]
